package db.migration;

import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.UUID;

/**
 * Adiciona {@code account.public_id} (UUID opaco) e tabela {@code refresh_token} para refresh com revogação.
 */
public class V16__Account_public_id_and_refresh_token extends BaseJavaMigration {

    @Override
    public void migrate(Context context) throws Exception {
        Connection connection = context.getConnection();
        try (Statement st = connection.createStatement()) {
            st.execute("ALTER TABLE account ADD COLUMN IF NOT EXISTS public_id UUID");
        }
        try (
                PreparedStatement select = connection.prepareStatement(
                        "SELECT id FROM account WHERE public_id IS NULL"
                )
        ) {
            ResultSet rs = select.executeQuery();
            while (rs.next()) {
                long accountId = rs.getLong(1);
                try (PreparedStatement up = connection.prepareStatement(
                        "UPDATE account SET public_id = ? WHERE id = ?"
                )) {
                    up.setObject(1, UUID.randomUUID());
                    up.setLong(2, accountId);
                    up.executeUpdate();
                }
            }
        }
        try (Statement st = connection.createStatement()) {
            st.execute("ALTER TABLE account ALTER COLUMN public_id SET NOT NULL");
        }
        try (Statement st = connection.createStatement()) {
            st.execute("CREATE UNIQUE INDEX IF NOT EXISTS uk_account_public_id ON account (public_id)");
        }
        try (Statement st = connection.createStatement()) {
            st.execute("""
                    CREATE TABLE IF NOT EXISTS refresh_token (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        account_id BIGINT NOT NULL,
                        token_hash VARCHAR(64) NOT NULL,
                        expires_at TIMESTAMP NOT NULL,
                        revoked_at TIMESTAMP NULL,
                        created_at TIMESTAMP NOT NULL,
                        CONSTRAINT fk_refresh_token_account FOREIGN KEY (account_id) REFERENCES account (id)
                    )
                    """);
        }
        try (Statement st = connection.createStatement()) {
            st.execute("CREATE UNIQUE INDEX IF NOT EXISTS uk_refresh_token_hash ON refresh_token (token_hash)");
        }
        try (Statement st = connection.createStatement()) {
            st.execute("CREATE INDEX IF NOT EXISTS idx_refresh_token_account ON refresh_token (account_id)");
        }
    }
}
