package db.migration;

import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

import java.sql.Statement;

/**
 * Tabela inicial de sessões de colaboração de texto com IA (nome histórico). Renomeada em V18 para
 * {@code account_text_ai_session}.
 */
public class V17__bishop_ministry_assistant_session extends BaseJavaMigration {

    @Override
    public void migrate(Context context) throws Exception {
        try (Statement st = context.getConnection().createStatement()) {
            st.execute("""
                    CREATE TABLE IF NOT EXISTS bishop_ministry_assistant_session (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        account_id BIGINT NOT NULL,
                        openai_thread_id VARCHAR(128),
                        title VARCHAR(500) NOT NULL,
                        resume VARCHAR(16000) NOT NULL,
                        time_considered BOOLEAN NOT NULL,
                        expected_minutes INTEGER NOT NULL,
                        created_at TIMESTAMP NOT NULL,
                        last_updated_at TIMESTAMP,
                        CONSTRAINT fk_bishop_ministry_session_account FOREIGN KEY (account_id) REFERENCES account (id)
                    )
                    """);
        }
        try (Statement st = context.getConnection().createStatement()) {
            st.execute("""
                    CREATE UNIQUE INDEX IF NOT EXISTS uk_bishop_ministry_openai_thread
                    ON bishop_ministry_assistant_session (openai_thread_id)
                    WHERE openai_thread_id IS NOT NULL
                    """);
        }
        try (Statement st = context.getConnection().createStatement()) {
            st.execute(
                    "CREATE INDEX IF NOT EXISTS idx_bishop_ministry_session_account ON bishop_ministry_assistant_session (account_id)"
            );
        }
    }
}
