package db.migration;

import br.com.mechanic.account.constant.EntityConstants;
import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.Statement;

/** Coluna {@code is_deleted} em {@code account_text_ai_session} e tabela {@code account_text_ai_session_history}. */
public class V19__account_text_ai_session_soft_delete_and_history extends BaseJavaMigration {

    @Override
    public void migrate(Context context) throws Exception {
        try (Statement st = context.getConnection().createStatement()) {
            if (!columnExists(context, EntityConstants.ACCOUNT_TEXT_AI_SESSION_TABLE_NAME, EntityConstants.COLUMN_IS_DELETED)) {
                st.execute(
                        "ALTER TABLE " + EntityConstants.ACCOUNT_TEXT_AI_SESSION_TABLE_NAME + " ADD COLUMN "
                                + EntityConstants.COLUMN_IS_DELETED + " BOOLEAN"
                );
            }
        }
        try (Statement st = context.getConnection().createStatement()) {
            st.execute(
                    """
                    CREATE TABLE IF NOT EXISTS %s (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        %s BIGINT NOT NULL,
                        %s BIGINT NOT NULL,
                        %s TIMESTAMP NOT NULL,
                        CONSTRAINT %s FOREIGN KEY (%s) REFERENCES %s (id),
                        CONSTRAINT %s FOREIGN KEY (%s) REFERENCES %s (id)
                    )
                    """
                            .formatted(
                                    EntityConstants.ACCOUNT_TEXT_AI_SESSION_HISTORY_TABLE_NAME,
                                    EntityConstants.COLUMN_TEXT_AI_SESSION_ID,
                                    EntityConstants.COLUMN_ACCOUNT_ID,
                                    EntityConstants.COLUMN_CREATED_AT,
                                    EntityConstants.ACCOUNT_TEXT_AI_SESSION_HISTORY_SESSION_FK_NAME,
                                    EntityConstants.COLUMN_TEXT_AI_SESSION_ID,
                                    EntityConstants.ACCOUNT_TEXT_AI_SESSION_TABLE_NAME,
                                    EntityConstants.ACCOUNT_TEXT_AI_SESSION_HISTORY_ACCOUNT_FK_NAME,
                                    EntityConstants.COLUMN_ACCOUNT_ID,
                                    EntityConstants.ACCOUNT_TABLE_NAME
                            )
            );
        }
        try (Statement st = context.getConnection().createStatement()) {
            st.execute(
                    "CREATE INDEX IF NOT EXISTS " + EntityConstants.ACCOUNT_TEXT_AI_SESSION_HISTORY_SESSION_IDX_NAME + " ON "
                            + EntityConstants.ACCOUNT_TEXT_AI_SESSION_HISTORY_TABLE_NAME + " ("
                            + EntityConstants.COLUMN_TEXT_AI_SESSION_ID + ")"
            );
        }
    }

    private static boolean columnExists(Context context, String tableName, String columnName) throws Exception {
        DatabaseMetaData meta = context.getConnection().getMetaData();
        try (ResultSet rs = meta.getColumns(null, null, tableName, columnName)) {
            return rs.next();
        }
    }
}
