CREATE TABLE topic_ai_report (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id BIGINT NOT NULL,
    topic_owner_account_id BIGINT NOT NULL,
    openai_model VARCHAR(128) NOT NULL,
    request_payload_json TEXT NOT NULL,
    response_payload_json TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_topic_ai_report_topic FOREIGN KEY (topic_id) REFERENCES topic (id),
    CONSTRAINT fk_topic_ai_report_owner FOREIGN KEY (topic_owner_account_id) REFERENCES account (id)
);

CREATE INDEX idx_topic_ai_report_topic_id ON topic_ai_report (topic_id);
CREATE INDEX idx_topic_ai_report_owner_id ON topic_ai_report (topic_owner_account_id);
